import {
  Terminal as TerminalIcon,
  Code2,
  Folder,
  Settings as SettingsIcon,
  Activity,
  Info,
  X,
  Minus,
  Square,
  Copy,
  Github,
  Star,
  FileText,
  FilePlus,
  FolderPlus,
  Play,
  Save,
  Trash2,
  ChevronRight,
  ChevronDown,
  Cpu,
  HardDrive,
  Power,
  Bot,
  Send,
  Loader2,
  LogOut,
  Sparkles,
  Cloud,
  Zap,
  Globe,
  Check,
  PanelLeftClose,
  PanelLeft,
  GripHorizontal,
  RefreshCw,
  ShieldAlert,
  BookOpen,
  LucideIcon,
} from "lucide-react";

export const APP_ICONS: Record<string, LucideIcon> = {
  terminal: TerminalIcon,
  code: Code2,
  folder: Folder,
  settings: SettingsIcon,
  activity: Activity,
  info: Info,
  globe: Globe,
};

// Maps each AppId to its icon key in APP_ICONS above. Keep this in sync with
// APP_META in lib/store.ts — every app must resolve to a real icon here.
export const APP_ICON_KEY: Record<string, string> = {
  terminal: "terminal",
  vexbit: "code",
  files: "folder",
  settings: "settings",
  monitor: "activity",
  about: "info",
  vexnet: "globe",
};

export function resolveAppIcon(app: string): LucideIcon {
  return APP_ICONS[APP_ICON_KEY[app] ?? app] ?? TerminalIcon;
}

export {
  TerminalIcon,
  Code2,
  Folder,
  SettingsIcon,
  Activity,
  Info,
  X,
  Minus,
  Square,
  Copy,
  Github,
  Star,
  FileText,
  FilePlus,
  FolderPlus,
  Play,
  Save,
  Trash2,
  ChevronRight,
  ChevronDown,
  Cpu,
  HardDrive,
  Power,
  Bot,
  Send,
  Loader2,
  LogOut,
  Sparkles,
  Cloud,
  Zap,
  Globe,
  Check,
  PanelLeftClose,
  PanelLeft,
  GripHorizontal,
  RefreshCw,
  ShieldAlert,
  BookOpen,
};
